{"timestamp":"2025-08-07T00:46:30.417185","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-07T00:46:30.418512","level":"info","event":"Filling up the DagBag from /home/cnguyen/myrepos/dbt-postgres-airflow/airflow/dags/dbt-orchesstrator.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-07T00:47:57.356404","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"AirflowRuntimeError","exc_value":"API_SERVER_ERROR: {'status_code': 409, 'message': 'Server returned error', 'detail': {'detail': {'reason': 'Unique constraint violation', 'statement': 'INSERT INTO rendered_task_instance_fields (dag_id, task_id, run_id, map_index, rendered_fields, k8s_pod_yaml) VALUES (?, ?, ?, ?, ?, ?)', 'orig_error': 'UNIQUE constraint failed: rendered_task_instance_fields.dag_id, rendered_task_instance_fields.task_id, rendered_task_instance_fields.run_id, rendered_task_instance_fields.map_index', 'message': 'Serious error when handling your request. Check logs for more details - you will find it in api server when you look for ID HLkI5qiT'}}}","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/cnguyen/.pyenv/versions/3.10.4/envs/demo_airflow/lib/python3.10/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":871,"name":"run"},{"filename":"/home/cnguyen/.pyenv/versions/3.10.4/envs/demo_airflow/lib/python3.10/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":778,"name":"_prepare"},{"filename":"/home/cnguyen/.pyenv/versions/3.10.4/envs/demo_airflow/lib/python3.10/site-packages/airflow/sdk/execution_time/comms.py","lineno":203,"name":"send"},{"filename":"/home/cnguyen/.pyenv/versions/3.10.4/envs/demo_airflow/lib/python3.10/site-packages/airflow/sdk/execution_time/comms.py","lineno":263,"name":"_get_response"},{"filename":"/home/cnguyen/.pyenv/versions/3.10.4/envs/demo_airflow/lib/python3.10/site-packages/airflow/sdk/execution_time/comms.py","lineno":250,"name":"_from_frame"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-07T00:47:57.476400Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-07T00:47:57.476676Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-07T00:47:57.476886Z","level":"info","event":"Task:<Task(ExternalTaskSensor): wait_for_weather_data>","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-07T00:47:57.476996Z","level":"info","event":"Failure caused by API_SERVER_ERROR: {'status_code': 409, 'message': 'Server returned error', 'detail': {'detail': {'reason': 'Unique constraint violation', 'statement': 'INSERT INTO rendered_task_instance_fields (dag_id, task_id, run_id, map_index, rendered_fields, k8s_pod_yaml) VALUES (?, ?, ?, ?, ?, ?)', 'orig_error': 'UNIQUE constraint failed: rendered_task_instance_fields.dag_id, rendered_task_instance_fields.task_id, rendered_task_instance_fields.run_id, rendered_task_instance_fields.map_index', 'message': 'Serious error when handling your request. Check logs for more details - you will find it in api server when you look for ID HLkI5qiT'}}}","chan":"stdout","logger":"task"}
