{"timestamp":"2025-08-07T10:06:44.837251","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-07T10:06:44.837794","level":"info","event":"Filling up the DagBag from /home/cnguyen/myrepos/dbt-postgres-airflow/airflow/dags/api-weather.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-07T10:06:44.895683Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-07T10:06:44.895831Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-07T10:06:44.895951Z","level":"info","event":"Current task name:ingest_weather_data","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-07T10:06:44.895998Z","level":"info","event":"Dag name:data_weather_fetch_daily","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-07T10:06:44.898292","level":"info","event":"Fetching data from WeatherStack API","logger":"helper_function"}
{"timestamp":"2025-08-07T10:06:45.946782","level":"info","event":"API response received successfully !!!","logger":"helper_function"}
{"timestamp":"2025-08-07T10:06:45.947075","level":"info","event":"Connecting to PostgreSQL database","logger":"helper_function"}
{"timestamp":"2025-08-07T10:06:45.947427","level":"error","event":"Failed to connect to PostgreSQL: connection to server at \"localhost\" (127.0.0.1), port 5000 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\n","logger":"helper_function","error_detail":[{"exc_type":"OperationalError","exc_value":"connection to server at \"localhost\" (127.0.0.1), port 5000 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/cnguyen/myrepos/dbt-postgres-airflow/airflow/utilities/helper_function.py","lineno":28,"name":"connect_to_postgres"},{"filename":"/home/cnguyen/.pyenv/versions/3.10.4/envs/demo_airflow/lib/python3.10/site-packages/psycopg2/__init__.py","lineno":122,"name":"connect"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-07T10:06:45.947656","level":"error","event":"An error occurred: connection to server at \"localhost\" (127.0.0.1), port 5000 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\n","logger":"helper_function","error_detail":[{"exc_type":"OperationalError","exc_value":"connection to server at \"localhost\" (127.0.0.1), port 5000 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/cnguyen/myrepos/dbt-postgres-airflow/airflow/utilities/helper_function.py","lineno":90,"name":"main"},{"filename":"/home/cnguyen/myrepos/dbt-postgres-airflow/airflow/utilities/helper_function.py","lineno":28,"name":"connect_to_postgres"},{"filename":"/home/cnguyen/.pyenv/versions/3.10.4/envs/demo_airflow/lib/python3.10/site-packages/psycopg2/__init__.py","lineno":122,"name":"connect"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-07T10:06:45.947833","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"UnboundLocalError","exc_value":"local variable 'conn' referenced before assignment","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/cnguyen/.pyenv/versions/3.10.4/envs/demo_airflow/lib/python3.10/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":877,"name":"run"},{"filename":"/home/cnguyen/.pyenv/versions/3.10.4/envs/demo_airflow/lib/python3.10/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1164,"name":"_execute_task"},{"filename":"/home/cnguyen/.pyenv/versions/3.10.4/envs/demo_airflow/lib/python3.10/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/cnguyen/.pyenv/versions/3.10.4/envs/demo_airflow/lib/python3.10/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/cnguyen/.pyenv/versions/3.10.4/envs/demo_airflow/lib/python3.10/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/cnguyen/.pyenv/versions/3.10.4/envs/demo_airflow/lib/python3.10/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/home/cnguyen/myrepos/dbt-postgres-airflow/airflow/utilities/helper_function.py","lineno":96,"name":"main"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-07T10:06:45.979746Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-07T10:06:45.979993Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-07T10:06:45.980055Z","level":"info","event":"Task:<Task(PythonOperator): ingest_weather_data>","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-07T10:06:45.980124Z","level":"info","event":"Failure caused by local variable 'conn' referenced before assignment","chan":"stdout","logger":"task"}
